{% set name = "pyavm" %}
{% set version = "0.9.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyAVM-{{ version }}.tar.gz
  sha256: 815efcca9bd8c2884799d8cfde537917decf7e6c6e57dd6dbf0e60b18799ee2f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  requires:
    - astropy
    - numpy
    - pillow
    - pytest
  imports:
    - pyavm
  commands:
    - pytest $SP_DIR/pyavm -p no:warnings   # [not win]
    - pytest %SP_DIR%/pyavm -p no:warnings  # [win]

about:
  home: http://astrofrog.github.io/pyavm/
  summary: Simple pure-python AVM meta-data handling
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - astrofrog
    - pkgw
