{% set name = "pyavm" %}
{% set version = "0.9.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ce11c279ec75bdf823d0c386124a1528a5e7b36fa5dd4d26499227939f117f88

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - astropy-base
    - numpy
    - pillow
    - pytest
    - python {{ python_min }}
  imports:
    - pyavm
  commands:
    - pip check
    - pytest $SP_DIR/pyavm -p no:warnings   # [not win]
    - pytest %SP_DIR%/pyavm -p no:warnings  # [win]

about:
  home: http://astrofrog.github.io/pyavm/
  summary: Simple pure-python AVM meta-data handling
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - astrofrog
    - pkgw
