{% set name = "pyavm" %}
{% set version = "0.9.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/PyAVM-{{ version }}.tar.gz
  sha256: b3b78b3e80070db63db4fb77440e73260f8db93b5557f4aaa54511dcdac6f26d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - astropy-base
    - numpy
    - pillow
    - pytest
    - python {{ python_min }}
  imports:
    - pyavm
    - pyavm._version
  commands:
    - pip check
    - pytest $SP_DIR/pyavm -p no:warnings   # [not win]
    - pytest %SP_DIR%/pyavm -p no:warnings  # [win]

about:
  home: http://astrofrog.github.io/pyavm/
  summary: Simple pure-python AVM meta-data handling
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - astrofrog
    - pkgw
